services:
  - type: web
    name: universal-rl-dashboard
    env: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "python dashboard.py"
    plan: free
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: PORT
        value: 9000